image:
    file: .gitpod.Dockerfile
tasks:
  - name: my gitpod yml
    init: |
      echo 'TODO: build project'
      echo 'try again'
      echo 'hellooo'
    command: |
      echo 'TODO: start app'
      echo 'something else'
